name: swiss-urbanization-post
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - -e .
    - python-dotenv>=0.5.1
    - awscli
    - awscli-plugin-endpoint==0.3
    - python-slugify==2.0.1
    - pylandstats==0.1.1
  - setuptools
  - wheel
  - flake8
  - sphinx
  - click
  - coverage
  - python=3.6
  - boto3=1.9.86
  - geopandas=0.4.0
  - matplotlib=3.0.2
  - numpy=1.15.4
  - rasterio=1.0.13  
  - tqdm=4.30.0  

