name: swiss-urbanization-post
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - -e .
    - python-dotenv>=0.5.1
    - awscli
  - setuptools
  - wheel
  - flake8
  - sphinx
  - click
  - coverage
  - python=3.6
